language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

before_script:
  - cp phpunit.xml.dist ./phpunit.xml
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install

script: vendor/phpunit/phpunit/phpunit

after_success:
  - curl -sL https://bit.ly/artifact-uploader | php
